name: Infra and App Deploy
on:
  push:
    branches:
      - main
    workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: BewareTheAzureDragon
  AZURE_APPSERVICE_PLAN: front-end-app-service-plan
  NODE_VERSION: "24.x"
jobs:
  validate-credentials:
    name: validate azure credentials
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Log in to Azure
        run: |
          az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: logout
        run: |
          az logout
