# 
name: deploy my infra and app
on: 
    workflow_dispatch:
    push: 
        branches:
            - main
env:
    AZURE_WEBAPP_NAME: BewareTheAzureDragon
    AZURE_APPSERVICE_PLAN: front-end-app-service-plan
    NODE_VERSION: "20.x"
jobs: 
    validate-credentials:
        name: validate azure creds
        runs-on: ubuntu-latest
        steps: 
            - name: checkout
              uses: actions/checkout@main

            - name: Log in to Azure
              run: |
                az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
  
            - name: logout
              run: |
                az logout
      